### ISSUE TITLE
'wsl --set-version Ubuntu-18.04 2'コマンド実行時のエラーについて

### ISSUE THREAD

**Issue by DaiGuard** [MicrosoftDocs/WSL.ja-JP#2]
WSL2にディストリビューションをアップデートする際、
仮想マシン プラットフォーム機能が有効になっていないと注意されます
Windowsnoの機能の有効化で確認しても有効にはなっています

他に何が考えられるでしょうか？

```
PS C:\WINDOWS\system32&gt; wsl --set-version Ubuntu-18.04 2
変換中です。この処理には数分かかることがあります...
WSL 2 との主な違いについては、https://aka.ms/wsl2 を参照してください
Windows の仮想マシン プラットフォーム機能を有効にして、BIOS で仮想化が有効になっていることを確認してください。          詳細については、https://aka.ms/wsl2-install を参照してください
```

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [WSL 2 のインストール](https://docs.microsoft.com/ja-jp/windows/wsl/wsl2-install#feedback)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL.ja-jp/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @DaiGuard
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@DaiGuard  様、 

ご投稿いただき、ありがとうございます。このフィードバックは製品に関連しているようです。ドキュメント ページの下部にある [製品フィードバックを送る] ボタンを使用して、提案を記録してください。 

ドキュメントに関連したフィードバックがある場合は、このチャネルを通して記録してください。 

記事への投稿に感謝しております。 

Microsoft DOCS International Team
